# Generated by Django 5.0.6 on 2024-06-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
